#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define SPEED 50
#define FRONT_ANGLE 0
#define BACK_ANGLE 1800
#define BLACK_LIGHT_VAL 40


void ride(int angle = FRONT_ANGLE){
	int g = SensorValue(gyro)-angle;
	motor(leftMotor) = SPEED-g*2;
	motor(rightMotor) = SPEED+g*2;
}

void rideForTime(int time, int angle = 0){
	clearTimer(T1);
	while (time1(T1)<time) ride(angle);
}

int cycle = 1;

task main()
{
	while (true){
		for (int i = 0; i < cycle; i++){
			rideForTime(1000,0);
			while(SensorValue(light)>BLACK_LIGHT_VAL) ride();
		}
		for (int i = 0; i < cycle; i++){
			rideForTime(1000,1800);
			while(SensorValue(light)>BLACK_LIGHT_VAL) ride(BACK_ANGLE);
		}
		cycle++;
	}
}
