#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define SPEED 60
#define MID_SPEED 30
#define LINE_TOLERANCE 50
#define LINE_SPEED 30
#define FOLLOW_POWER 6


void ride(int vLeft, int vRight, int time, bool useGyro, int deg = 0){
	int g =0;
	if (useGyro) g = SensorValue(gyro)-deg;
	motor(leftMotor) = vLeft-2*g;
	motor(rightMotor) = vRight+2*g;
	wait1Msec(time);
}

void approachAndFollowLine(){
	while (SensorValue(light)>40) ride(SPEED,SPEED*0.95,0,false);
	int diff;
	while(SensorValue[sonar]>30)
	{
			diff=FOLLOW_POWER*(SensorValue(light)-LINE_TOLERANCE);
			motor(leftMotor)=LINE_SPEED-diff;
			motor(rightMotor)=LINE_SPEED+diff;
	}
}

task main()
{
	approachAndFollowLine();
	while(SensorValue(light)>40) ride(SPEED,SPEED,0,true);
	while(SensorValue(gyro)<900) ride(SPEED,MID_SPEED,0,false);
	while(SensorValue(light)>40) ride(SPEED,SPEED,0,true,900);
	while(SensorValue(gyro)<1800) ride(SPEED,MID_SPEED,0,false);
	approachAndFollowLine();
	while(true) ride(SPEED,SPEED,0,true,1800);
}
