#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// DISCLAIMER:
//
// This challenge is somehow broken, you cannot finish it in the latest
// version, this code is made to be successfull if RVW would work properly

#define SPEED 60
#define LINE_TOLERANCE 40
#define LINE_SPEED 60
#define FOLLOW_POWER 8
#define SONAR_LINE_END_VALUE 60
#define GO_WITHOUT_SENSING 2000
#define RED_BOOK_SONAR 40
#define GREEN_BOOK_SONAR 24
#define TIMER_UNTIL_FINISH 400


void go(int deg = 0, int time = 1, bool backwards = false)
{
	clearTimer(T1);
	while (time1(T1) < time){
		int g=SensorValue(gyro)-deg;
		motor(leftMotor)=(backwards ? -1 : 1)*SPEED-2*g;
		motor(rightMotor)=(backwards ? -1 : 1)*SPEED+2*g;
	}
}


task main()
{
	while(SensorValue(touch) == 0) go(); //drive until object colision
	while(SensorValue(sonar) < 70) go(0,1,true); //go backwards
	while(SensorValue(light)>40) go(-450); //line approach

	int diff; // differencial value
	while(SensorValue(sonar) > SONAR_LINE_END_VALUE)
	{
			diff=FOLLOW_POWER*(SensorValue[light]-LINE_TOLERANCE); //calculate difference
			motor(leftMotor)=LINE_SPEED-diff;
			motor(rightMotor)=LINE_SPEED+diff;
	} //follows line until sonar is measuring obstacle in distance

	while(SensorValue(sonar) > RED_BOOK_SONAR) go(-1800); //red book approach
	while(SensorValue(sonar) > GREEN_BOOK_SONAR) go(-900); //green book approach
  go(-50,GO_WITHOUT_SENSING); //go in -5deg to not hit that yellow cup
	while(SensorValue(light) > 40) go(); //go until finish
	go(0,TIMER_UNTIL_FINISH); //last drive into finish square
}
