#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define SPEED 60
#define LINE_TOLERANCE 40
#define LINE_SPEED 40
#define FOLLOW_POWER 4
#define SONAR_LINE_END_VALUE 60
#define STOP_LIGHT_MEASURE_TIME 1000
#define BOOK_SONAR_DISTANCE 30
#define ROTATE_SPEED 16
#define TIMER_UNTIL_FINISH 400


void ride(int speedLeft, int speedRight, int time, bool gyroDiffOn)
{
	int g=0;
	if(gyroDiffOn) g=SensorValue[gyro];
	motor(leftMotor)=speedLeft-2*g;
	motor(rightMotor)=speedRight+2*g;
	if(time>0) wait1Msec(time);
}

task main()
{
	while(SensorValue(touch)==0) ride(SPEED,SPEED,0,true); //drive until object colision
	ride(-SPEED,-SPEED,2000,true); //go backwards
	ride(-SPEED,SPEED,350,false); //rotate
	while(SensorValue(light)>40) ride(SPEED,SPEED,0,false); //line approach

	int diff; // differencial value
	while(SensorValue[sonar]>SONAR_LINE_END_VALUE)
	{
			diff=FOLLOW_POWER*(SensorValue[light]-LINE_TOLERANCE); //calculate difference
			motor[leftMotor]=LINE_SPEED-diff;
			motor[rightMotor]=LINE_SPEED+diff;
	} //follows line until sonar is measuring obstacle in distance

	while(SensorValue(sonar)>BOOK_SONAR_DISTANCE) ride(SPEED,SPEED,0,false); //book approach
	while(SensorValue(gyro)<0) ride(SPEED,ROTATE_SPEED,0,false); //rotates right until it is 0 on gyro
	clearTimer(T1); //clear timer
	while (time1[T1]<STOP_LIGHT_MEASURE_TIME) ride(SPEED,SPEED,0,true); //drive until time elapsed
	while(SensorValue(light)>LINE_TOLERANCE) ride(SPEED,SPEED,0,true); //drive to finish
	clearTimer(T1); //clear timer
	while (time1[T1]<TIMER_UNTIL_FINISH) ride(SPEED,SPEED,0,true); //drive to the middle of square
}
