#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define SPEED 60

void ride(int vLeft, int vRight, int time, bool useGyro, int deg = 0){
	int g =0;
	if (useGyro) g = SensorValue(gyro)-deg;
	motor(leftMotor) = vLeft-2*g;
	motor(rightMotor) = vRight+2*g;
	wait1Msec(time);
}

task main(){
	int curDeg = 0;
	while (true){
		while (SensorValue(touch)==0) ride(SPEED,SPEED,0,true,curDeg);
		clearTimer(T1);
		while(time1[T1]<200) ride(-SPEED,-SPEED,0,true,curDeg);
		while(SensorValue(touch)==0) ride(SPEED,SPEED,0,true,curDeg+900);
		curDeg+=900;
	}
}
