#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SPEED 60
#define START_DRIVE_TIME 3750
#define DEF_DRIVE_TIME 4750
#define DEGREE_MULTIPLIER 900

task main(){
	int deg = 0;
	while (true){
		clearTimer(T1);
		while (time1(T1) < (curDeg > 0 ? START_DRIVE_TIME : DEF_DRIVE_TIME)){
			int g = SensorValue(gyro)-deg;
			motor(leftMotor) = SPEED-2*g;
			motor(rightMotor) = SPEED+2*g;
		}
		deg+=DEGREE_MULTIPLIER;
	}
}
