#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define SPEED 60

void ride(int time, int deg = 0){
	clearTimer(T1);
	while (time1(T1) < time){
		int g = SensorValue(gyro)-deg;
		motor(leftMotor) = SPEED-2*g;
		motor(rightMotor) = SPEED+2*g;
	}
}

task main(){
	int curDeg = 0;
	while (true){
		ride(curDeg > 0 ? 4750 : 3750, curDeg);
		curDeg+=900;
	}
}
