#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DISTANCE 900
#define FREQUENCY 1900
#define SPEED 50

float deg = -700;

task main()
{
	while(true){
		int g = SensorValue(gyro)-(deg < 0 ? 450 : cos(deg/(float)FREQUENCY)*DISTANCE);
		motor(leftMotor) = SPEED-g*2;
		motor(rightMotor) = SPEED+g*2;
		deg++;
		wait1Msec(1);
	}
}
