#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void ride(int speedLeft, int speedRight, int time, bool gyroDiffOn)
{
	int g=0;
	if(gyroDiffOn) g=SensorValue[gyro];
	motor(leftMotor)=speedLeft-2*g;
	motor(rightMotor)=speedRight+2*g;
	if(time>0) wait1Msec(time);
}
int attendance = 0;

void checkAttendance(){
    if (SensorValue(sonar) < 50) attendance++;
}

task main()
{
	for (int i = 0; i < 3; i++){
		ride(50,50,300,true); //for skipping current line or start line
	  while (SensorValue(light)>40) ride(50,50,0,true); //stop when black line occurs
	  while (SensorValue(gyro)<900) ride(50,-50,0,false); //rotate right
	  checkAttendance();
	  while (SensorValue(gyro)>-900) ride(-50,50,0,false); //rotate left
	  checkAttendance();
	  while (SensorValue(gyro)<0) ride(50,-50,0,false); //rotate back
	}
  nxtDisplayTextLine(0, "Attendance: %d",attendance); //display attendance
}
