#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SPEED 50
#define SONAR_CHECK_VALUE 50
#define NO_SENSING_DRIVE_TIME 300
#define ROWS 3
#define BLACK_LINE_VALUE 40

void go(int deg = 0, int time = 1)
{
	clearTimer(T1);
	while (time1(T1) < time){
		int g = SensorValue(gyro)-deg;
		motor(leftMotor)=SPEED-2*g;
		motor(rightMotor)=SPEED+2*g;
	}

}


int attendance = 0;

void checkAttendance(){
    if (SensorValue(sonar) < SONAR_CHECK_VALUE) attendance++;
}

task main()
{
	for (int i = 0; i < ROWS; i++){
		go(0, NO_SENSING_DRIVE_TIME); //for skipping current line or start line
	  while (SensorValue(light) > BLACK_LINE_VALUE) go(); //stop when black line occurs
	  while (SensorValue(gyro) < 900) go(900); //rotate right
	  checkAttendance();
	  while (SensorValue(gyro) > -900) go(-900); //rotate left
	  checkAttendance();
	}
	while (SensorValue(gyro) < 0) go(); //return back
  nxtDisplayTextLine(0, "Attendance: %d", attendance); //display attendance
}
