#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SPEED 50

void setMotors(int vLeft, int vRight)
{
	motor(rightMotor) = vLeft;
	motor(leftMotor) = vRight;
}

task main()
{
	int maxLight = SensorValue(light);
	setMotors(SPEED,-SPEED);
	while (SensorValue(gyro) > -3600)
		maxLight = SensorValue(light) > maxLight ? SensorValue(light) : maxLight;
	while (SensorValue(light) != maxLight){}
	wait1Msec(50);
  setMotors(SPEED,SPEED);
	while (SensorValue(touch) == 0) {}
}
